spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mybatis?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
    username: root
    password: qwe!23
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    # 不设置initialization-mode: always 不会加载 sql
    initialization-mode: always
    continue-on-error: true
    schema:
      - "classpath:db/schema.sql"
    data:
      - "classpath:db/data.sql"
    hikari:
      minimum-idle: 5
      connection-test-query: SELECT 1 FROM DUAL
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      pool-name: SpringBootDemoHikariCP
      max-lifetime: 60000
      connection-timeout: 30000

#动态数据源可以进行切换
#spring:
#  datasource:
#    initialization-mode: always
#    continue-on-error: true
#    schema:
#      - "classpath:db/schema.sql"
#    data:
#      - "classpath:db/data.sql"
#    dynamic:
#      p6spy: true # 是否开启 SQL日志输出，生产环境建议关闭，有性能损耗
#      hikari:
#        connection-timeout: 30000
#        max-lifetime: 1800000
#        max-pool-size: 15
#        min-idle: 5
#        connection-test-query: select 1
#        pool-name: HikariCP
#      primary: base # 配置默认数据源
#      datasource:
#        base: # 数据源-1，名称为 base
#          username: root
#          password: qwe!23
#          driver-class-name: com.mysql.jdbc.Driver
#          url: jdbc:mysql://192.168.1.233:3306/mybatis?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8&useSSL=false



logging:
  level:
    com.sunzi.demoormmybatis.demo: debug
    com.sunzi.demoormmybatis.demo.mapper: trace

mybatis:
  mapper-locations: classpath:mapper/*/*Mapper.xml
  #配置类型别名 在mapper中不用写全名
  type-aliases-package: com.sunzi.demoormmybatis.demo.entity
  configuration:
    #数据库中与实体类的字段名对应
   map-underscore-to-camel-case: true




